# Project information
site_name: Taller de Git
site_url: "https://github.com/aulasoftwarelibre/taller-de-git.git"
site_author: "Aula de Software Libre <aulasoftwarelibre@uco.es>"
site_description: "Curso b치sico de git"

# Repository information
repo_name: "aulasoftwarelibre/taller-de-git"
repo_url: "https://github.com/aulasoftwarelibre/taller-de-git.git"

# License
copyright: Copyleft - CC BY-NC 4.0 - Aula de Software Libre

# Configuration
theme:
  favicon: "images/logoasl.png"
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - navigation.instant
    - navigation.footer
    - navigation.tracking
  icon:
    logo: material/git
  name: "material"
  language: "es"
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to system preference

extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/aulasoftwarelibre"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/aulasl"
    - icon: fontawesome/brands/facebook
      link: "https://facebook.com/aulasl"
    - icon: fontawesome/brands/instagram
      link: "https://instagram.com/aulasoftwarelibre"
    - icon: fontawesome/brands/youtube
      link: "https://www.youtube.com/c/AulaSoftwareLibre"
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/company/aulasoftwarelibre/"
  analytics:
    provider: google
    property: UA-51754922-1

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - social
  - git-revision-date-localized:
      type: date

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true

# Page tree
nav:
  - Inicio: index.md
  - Sistemas de control de versiones: cvs.md
  - Introducci칩n a git: introduccion.md
  - Aspectos b치sicos de Git: git.md
  - Uso b치sico de Git: usobasico.md
  - Uso avanzado de Git: usoavanzado.md
  - Ramas: ramas.md
  - Github: github.md
  - Citar proyectos en GitHub: github-zenodo.md
  - Flujo de trabajo en GitHub: github-flow.md
  - Github avanzado: github-avanzado.md
  - Comandos de git: commands.md
  - Flujo de trabajo con Git: gitflow.md
  - Referencias: referencias.md
