site_name: Taller de Git
site_author: "Sergio Gómez <sergio@uco.es>"
site_description: "Curso básico de git"
site_url: "https://github.com/aulasoftwarelibre/taller-de-git.git"

repo_name: "aulasoftwarelibre/taller-de-git"
repo_url: "https://github.com/aulasoftwarelibre/taller-de-git.git"

theme:
  favicon: "images/logoasl.png"
  features:
    - instant
  icon:
    logo: material/git
  name: "material"
  language: "es"
  palette:
    - scheme: slate
      primary: gray
      accent: gray

plugins:
  - awesome-pages
  - git-revision-date-localized:
      type: date
  - search

extra_css: [extra.css]
extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/aulasoftwarelibre"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/aulasl"
    - icon: fontawesome/brands/facebook
      link: "https://facebook.com/aulasl"
    - icon: fontawesome/brands/instagram
      link: "https://instagram.com/aulasoftwarelibre"
    - icon: fontawesome/brands/youtube
      link: "https://www.youtube.com/channel/UCfWiR5j-cbKcGTi9faK8P6w"

markdown_extensions:
  - admonition: ~
  - attr_list: ~
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list: ~
  - footnotes: ~
  - toc:
      permalink: true
  - pymdownx.keys: ~

google_analytics:
  - "UA-51754922-1"
  - "auto"
