name: Build documentation

on:
  push:
    branches: 
      - master
      - main

jobs:
  # Build and deploy documentation site
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source form GitHub
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.13"
          version: "0.9.5"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: |
          uv sync --locked --all-extras --dev

      - name: Deploy
        run: |
          uv run mkdocs gh-deploy --force
